server:
  port: 9001
 host: react-admin.com

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/react-admin?characterEncoding=utf-8
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 10000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      table-prefix: at_
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    object-wrapper-factory: com.baomidou.mybatisplus.extension.MybatisMapWrapperFactory

jwt:
  secret: zz

Encryption:
     secretKey: 9!#95hsup*&$1zq7

TxCos:
  bucket: react-admin-1259742707
  region: ap-shanghai
  secretId:  AKIDW6mV6XrzymSwHxmV6gHnFGD9wVtQ7BRc
  secretKey: 3AIH6mDvX8brsgGcmjTCmAreIl5HMGDl
  url: https://react-admin-1259742707.cos.ap-shanghai.myqcloud.com
  uploadPath: react-admin